### PR TITLE
Update all dependencies

### LINKED ISSUE #16: Prepare for 0.4.0.x release
Need new branch to work with it

### PR DESCRIPTION
**Pull request by mibmo**
Bumps dependencies.
| Dependency | Old tag                | New tag                 |
| -----------| ---------------------- | ----------------------- |
| OpenSSL    | `OpenSSL_1_0_2p`       | `OpenSSL_1_1_1o`        |
| Libevent   | `release-2.1.8-stable` | `release-2.1.12-stable` |
| zlib       | `v1.2.11`              | `v1.2.12`               |
| XZ Utils   | `v5.2.4`               | `v5.2.5`                |
| Tor        | `tor-0.3.5.7`          | `tor-0.4.7.7`           |

Tests aren't working yet, as this requires updating Bine as well.

Unblocks #35
Somewhat closes #16

### CODE REVIEW

**Comment by cretz** [comment]
I wonder if it might be worth/necessary to update any dependencies? Especially OpenSSL if at all possible.

**Comment by mibmo** [comment]
> Can you confirm this version of Tor works w/ your Bine PR?

Yep :+1: 

> Also, I wonder if it might be worth/necessary to update any dependencies? Especially OpenSSL if at all possible.

That's probably a good idea; I'll bump all the dependencies. Perhaps it'd be possible to get dependabot running? not sure if it can handle submodules though.

**Review by cretz — APPROVED** [review]

**Comment by cretz** [comment]
Looks good! Feel free to merge if it builds well with all new dependencies. Can see about getting dependabot running a bit later, but yeah unsure about submodules.

**Comment by mibmo** [comment]
I haven't tested it thoroughly yet (it builds), so I'll wait on OK-ing the merge, but I hope to get it done soon-ish :)

**Comment by mibmo** [comment]
Alright, I've tested again & seems to be the exact same (tested with CI as well).

Wouldn't mind if you tested it as well, but that's not _strictly_ necessary. :)

**Comment by cretz** [comment]
Merged

**Pull request merged**
