### PR TITLE
Implement basic CI/CD with travis

### PR DESCRIPTION
**Pull request by ciehanski**
Let me know if there are any issues or questions.

### CODE REVIEW

**Comment by cretz** [comment]
Yay. I will look into merging tomorrow.

**Comment by cretz** [comment]
Ok, I'm gonna squash and merge this. I am going to make a couple of changes to the test afterwards and then do Windows support in #18.

**Comment by ciehanski** [comment]
Just saw that build_test.go still has old references to `ciehanski/bine`. Might be easier to update from your side instead of another PR.

https://github.com/cretz/tor-static/blob/0d42cc1abc5a54d60738cf63c194dd883c254220/build_test.go#L13

**Comment by cretz** [comment]
It is. I am shrinking it too.

**Pull request merged**
