### PR TITLE
add --static for zlib

### PR DESCRIPTION
**Pull request by lkebin**
Add --static flag to compile into static library only

### CODE REVIEW

**Comment by cretz** [comment]
Hrmm, I wonder why this wasn't needed before. Did it assume `--static` + more before and this is just limiting it? (sorry, not at a place I can test this and we don't really have a worthy CI)

**Comment by lkebin** [comment]
I'm not sure why it wasn't needed before.
Currently, I'm using bine package, if zlib/dist/lib directory includes dynamic library file, cgo will link zlib as dynamic link.

**Comment by cretz** [comment]
:+1: Will just merge and keep my eye out for any complaints

**Comment by lkebin** [comment]
Thanks!

**Pull request merged**
